[package]
name = "graphviz-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
c2rust-bitfields = "0.3"
f128 = "0.2"
libc = "0.2"
num-traits = "0.2"
